/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RoomId = IDL.Text;
export const UserProfile = IDL.Record({ 'username' : IDL.Text });
export const Time = IDL.Int;
export const Phase = IDL.Variant({ 'focus' : IDL.Null, 'pause' : IDL.Null });
export const Session = IDL.Record({
  'startTime' : Time,
  'isPause' : IDL.Bool,
  'phase' : Phase,
});
export const UniqueCode = IDL.Text;

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createRoom' : IDL.Func([], [IDL.Text], []),
  'getBurntCategories' : IDL.Func([], [IDL.Vec(RoomId)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentCategory' : IDL.Func([], [IDL.Opt(RoomId)], ['query']),
  'getPreviousCategories' : IDL.Func([], [IDL.Vec(RoomId)], ['query']),
  'getTimerState' : IDL.Func([IDL.Text], [IDL.Opt(Session)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinRoom' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startSession' : IDL.Func([IDL.Text, Phase], [], []),
  'storeEvent' : IDL.Func([IDL.Text, IDL.Opt(Phase), Time], [UniqueCode], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RoomId = IDL.Text;
  const UserProfile = IDL.Record({ 'username' : IDL.Text });
  const Time = IDL.Int;
  const Phase = IDL.Variant({ 'focus' : IDL.Null, 'pause' : IDL.Null });
  const Session = IDL.Record({
    'startTime' : Time,
    'isPause' : IDL.Bool,
    'phase' : Phase,
  });
  const UniqueCode = IDL.Text;
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createRoom' : IDL.Func([], [IDL.Text], []),
    'getBurntCategories' : IDL.Func([], [IDL.Vec(RoomId)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentCategory' : IDL.Func([], [IDL.Opt(RoomId)], ['query']),
    'getPreviousCategories' : IDL.Func([], [IDL.Vec(RoomId)], ['query']),
    'getTimerState' : IDL.Func([IDL.Text], [IDL.Opt(Session)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinRoom' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startSession' : IDL.Func([IDL.Text, Phase], [], []),
    'storeEvent' : IDL.Func([IDL.Text, IDL.Opt(Phase), Time], [UniqueCode], []),
  });
};

export const init = ({ IDL }) => { return []; };