/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RoomId = IDL.Text;
export const UserProfile = IDL.Record({
  'xp' : IDL.Nat,
  'username' : IDL.Text,
});
export const SignalType = IDL.Variant({
  'iceCandidate' : IDL.Null,
  'offer' : IDL.Null,
  'answer' : IDL.Null,
});
export const Signal = IDL.Record({
  'to' : IDL.Principal,
  'from' : IDL.Principal,
  'payload' : IDL.Text,
  'signalType' : SignalType,
});
export const SignalResponse = IDL.Record({ 'data' : IDL.Vec(Signal) });
export const Time = IDL.Int;
export const UniqueCode = IDL.Text;

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'awardXp' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'clearSignals' : IDL.Func([IDL.Text], [], []),
  'createRoom' : IDL.Func([], [IDL.Text], []),
  'getBurntCategories' : IDL.Func([], [IDL.Vec(RoomId)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentCategory' : IDL.Func([], [IDL.Opt(RoomId)], ['query']),
  'getPreviousCategories' : IDL.Func([], [IDL.Vec(RoomId)], ['query']),
  'getRoomParticipants' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinRoom' : IDL.Func([IDL.Text], [], []),
  'receiveSignals' : IDL.Func([IDL.Text], [SignalResponse], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendSignal' : IDL.Func(
      [IDL.Text, IDL.Principal, SignalType, IDL.Text],
      [],
      [],
    ),
  'storeEvent' : IDL.Func([IDL.Text, Time], [UniqueCode], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RoomId = IDL.Text;
  const UserProfile = IDL.Record({ 'xp' : IDL.Nat, 'username' : IDL.Text });
  const SignalType = IDL.Variant({
    'iceCandidate' : IDL.Null,
    'offer' : IDL.Null,
    'answer' : IDL.Null,
  });
  const Signal = IDL.Record({
    'to' : IDL.Principal,
    'from' : IDL.Principal,
    'payload' : IDL.Text,
    'signalType' : SignalType,
  });
  const SignalResponse = IDL.Record({ 'data' : IDL.Vec(Signal) });
  const Time = IDL.Int;
  const UniqueCode = IDL.Text;
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'awardXp' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'clearSignals' : IDL.Func([IDL.Text], [], []),
    'createRoom' : IDL.Func([], [IDL.Text], []),
    'getBurntCategories' : IDL.Func([], [IDL.Vec(RoomId)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentCategory' : IDL.Func([], [IDL.Opt(RoomId)], ['query']),
    'getPreviousCategories' : IDL.Func([], [IDL.Vec(RoomId)], ['query']),
    'getRoomParticipants' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinRoom' : IDL.Func([IDL.Text], [], []),
    'receiveSignals' : IDL.Func([IDL.Text], [SignalResponse], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendSignal' : IDL.Func(
        [IDL.Text, IDL.Principal, SignalType, IDL.Text],
        [],
        [],
      ),
    'storeEvent' : IDL.Func([IDL.Text, Time], [UniqueCode], []),
  });
};

export const init = ({ IDL }) => { return []; };